IDENTIFICATION DIVISION.
PROGRAM-ID. CREDENTIALS.

DATA DIVISION.
FILE SECTION.
FD CREDENTIAL-FILE.
01 CREDENTIAL-RECORD.
   05 USERNAME PIC X(20).
   05 PASSWORD PIC X(20).

WORKING-STORAGE SECTION.
01 USER-INPUT.
   05 USERNAME-INPUT PIC X(20).
   05 PASSWORD-INPUT PIC X(20).

PROCEDURE DIVISION.
MAIN-LOGIC.
    DISPLAY "Enter username: "
    ACCEPT USERNAME-INPUT
    DISPLAY "Enter password: "
    ACCEPT PASSWORD-INPUT

    OPEN OUTPUT CREDENTIAL-FILE
    MOVE USERNAME-INPUT TO USERNAME
    MOVE PASSWORD-INPUT TO PASSWORD
    WRITE CREDENTIAL-RECORD
    CLOSE CREDENTIAL-FILE

    DISPLAY "Credentials stored successfully."
    STOP RUN.
